hacarta/application/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Required

class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired()])
    password = PasswordField('Senha', validators=[DataRequired()])
    submit   = SubmitField('Entrar')

class SignupForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired()])
    password = PasswordField('Senha', validators=[DataRequired()])
    submit   = SubmitField('Registar')

hacarta/application/users/__init__.py
from .routes import bp

hacarta/application/users/routes.py
from flask import abort, Blueprint, current_app as app, redirect, render_template, request, url_for
from flask_login import UserMixin, login_required, login_user, logout_user
from urllib.parse import urlparse, urljoin

from .use_cases import *
from .forms import *

bp = Blueprint('users', __name__, template_folder='templates', static_folder='static')
app.login_manager.login_view = 'users.login'
repo = app.repositories['users']

@app.login_manager.user_loader
def load_user(user_id):
    result = get_user(repo, user_id)

    if result['success']:
        return _User.from_dto(result['user'])

@bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        email  = form.email.data
        pwd    = form.password.data
        result = authenticate_user(repo, email, pwd)

        if not result['success']:
            if 'email' in result['fields']:
                form.email.errors.append(result['fields']['email'])
            if 'pwd' in result['fields']:
                form.password.errors.append(result['fields']['pwd'])

            return render_template('users/login.html', form=form)

        login_user(_User.from_dto(result['user']))

        next = request.args.get('next')
        if not _is_safe_url(next):
            return abort(400)

        return redirect(next or url_for('restaurants.add'))
    return render_template('users/login.html', form=form)

@bp.route('/signup', methods=['GET', 'POST'])
def signup():
    form = SignupForm()
    if form.validate_on_submit():
        email  = form.email.data
        pwd    = form.password.data
        result = register_user(repo, email, pwd)

        if not result['success']:
            if 'email' in result['fields']:
                form.email.errors.append(result['fields']['email'])
            if 'pwd' in result['fields']:
                form.password.errors.append(result['fields']['pwd'])

            return render_template('users/login.html', form=form)

        login_user(_User.from_dto(result['user']))

        next = request.args.get('next')
        if not _is_safe_url(next):
            return abort(400)

        return redirect(next or url_for('restaurants.add'))
    return render_template('users/signup.html', form=form)

@bp.route('/logout', methods=['GET'])
@login_required
def logout():
    logout_user()

    return redirect(url_for('landing_page'))

def _is_safe_url(target):
    ref_url = urlparse(request.host_url)
    test_url = urlparse(urljoin(request.host_url, target))

    is_http = test_url.scheme in ('http', 'https')
    in_app = ref_url.netloc == test_url.netloc

    return is_http and in_app

class _User(dict, UserMixin):
    def __init__(self, id, email):
        super().__init__()

        self.id   = id    ## so flask login knows
        self.mail = email

    @classmethod
    def from_dto(cls, user_dto):
        return cls(user_dto['id'], user_dto['email'])

    def to_dto(self):
        return {'id': self.id, 'email': self.mail}

hacarta/application/users/templates/users/login.html
{% extends "base/sb-auth.html" %}

{% block title %}Login{% endblock %}

{% block page %}
  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Há Carta!</h1>
                  </div>
                  <form class="user" action="" method="post" novalidate>
                    {{ form.hidden_tag() }}

                    <div class="form-group">
                      {{ form.email(class='form-control form-control-user', placeholder='Email') }}
                      {% for error in form.email.errors %}
                      <small class="form-text text-danger">{{ error }}</small>
                      {% endfor %}
                    </div>

                    <div class="form-group">
                      {{ form.password(class='form-control form-control-user', placeholder='Senha') }}
                      {% for error in form.password.errors %}
                        <small class="form-text text-danger">{{ error }}</small>
                      {% endfor %}
                    </div>

                    {{ form.submit(class='btn btn-primary btn-user btn-block') }}
                  </form>
                  <hr>
                  <div class="text-center">
                    <a class="small" href="{{ url_for('users.signup') }}">Criar conta!</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>
{% endblock %}

hacarta/application/users/templates/users/signup.html
{% extends "base/sb-auth.html" %}

{% block title %}Signup{% endblock %}

{% block page %}
  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block bg-register-image"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Registe-se no Há Carta!</h1>
                  </div>
                  <form class="user" action="" method="post" novalidate>
                    {{ form.hidden_tag() }}

                    <div class="form-group">
                      {{ form.email(class='form-control form-control-user', placeholder='Email') }}
                      {% for error in form.email.errors %}
                      <small class="form-text text-danger">{{ error }}</small>
                      {% endfor %}
                    </div>

                    <div class="form-group">
                      {{ form.password(class='form-control form-control-user', placeholder='Senha') }}
                      {% for error in form.password.errors %}
                        <small class="form-text text-danger">{{ error }}</small>
                      {% endfor %}
                    </div>

                    {{ form.submit(class='btn btn-primary btn-user btn-block') }}
                  </form>
                  <hr>
                  <div class="text-center">
                    <a class="small" href="{{ url_for('users.login') }}">Já tem conta? Inicie sessão!</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>
{% endblock %}