hacarta/application/restaurants/routes.py
from flask import Blueprint, current_app as app, render_template, redirect, request, url_for
from flask_login import current_user as user, login_required

from .use_cases import *
from .forms import *

bp = Blueprint(
    'restaurants',
    __name__,
    template_folder='templates',
    static_folder='static',
)
repo = app.repositories['restaurants']



##
## public views use the restaurant slug to identify a restaurant
##

@app.route('/t/qrcode/<slug>')
@bp.route('/<slug>')
def home(slug):
    return _build_public_view('restaurant', slug)

@bp.route('/<slug>/menu')
def menu(slug):
    return _build_public_view('menu', slug)

def _build_public_view(view_name, slug):
    result = view_restaurant(repo, slug=slug)

    if result['success']:
        view = {'restaurant': result['restaurant']}
        return render_template(f'restaurants/{view_name}.html', **view)

    return redirect(url_for('landing_page'))



##
## authenticated views use the restaurant id and user to identify a restaurant
##

@bp.route('/manage/add', methods=['GET', 'POST'])
@login_required
def add():
    form = AddRestaurant()
    if form.validate_on_submit():
        name    = form.name.data
        result  = register_restaurant(repo, user.id, name)

        if not result['success']:
            if 'name' in result['fields']:
                form.name.errors.append(result['fields']['name'])
                return render_template(
                    'restaurants/add_restaurant.html',
                    form=form
                )
        id = result['restaurant']['id']
        return redirect(url_for('restaurants.edit', restaurant_id=id))

    return render_template('restaurants/add_restaurant.html', form=form)

@bp.route('/manage')
@login_required
def manage():
    result = view_owned_restaurants(repo, user.id)

    return render_template('restaurants/list_restaurants.html', **result)

@bp.route('/manage/<restaurant_id>', methods=['GET', 'POST'])
@login_required
def edit(restaurant_id):
    result = view_owned_restaurant(repo, restaurant_id, user.id)

    if not result['success']:
        return redirect(url_for('restaurants.manage'))

    restaurant = result['restaurant']
    form = EditRestaurant(restaurant)
    if form.validate_on_submit():
        request = {
            'id'            : restaurant_id,
            'description': form.description.data,
            'information': form.footer.data,
        }
        result = edit_restaurant(repo, **request)
        if not result['success']:
            redirect(url_for('restaurants.manage'))

        restaurant = result['restaurant']

    view = {'restaurant': restaurant, 'form': form}
    return render_template('restaurants/edit_restaurant.html', **view)

@bp.route('/manage/<restaurant_id>/categories/add', methods=['GET', 'POST'])
def add_category(restaurant_id):
    result = view_owned_restaurant(repo, restaurant_id, user.id)

    if not result['success']:
        return redirect(url_for('restaurants.manage'))

    form = AddCategory()
    if form.validate_on_submit():
        name   = form.name.data
        result = add_category(repo, restaurant_id, name)

        if result['success']:
            params = {'restaurant_id': restaurant_id}
            return redirect(url_for('restaurants.list_categories', **params))

        if 'name' in result['fields']:
            form.name.errors.append(result['fields']['name'])

    view = {**result, 'form': form}
    return render_template('restaurants/add_edit_category.html', **view)

@bp.route('/manage/<restaurant_id>/categories')
@login_required
def list_categories(restaurant_id):
    result = view_owned_restaurant(repo, restaurant_id, user.id)

    if not result['success']:
        return redirect(url_for('restaurants.manage'))

    return render_template('restaurants/list_categories.html', **result)

@bp.route(
    '/manage/<restaurant_id>/categories/<category_id>',
    methods=['GET', 'POST'],
)
@login_required
def edit_category(restaurant_id, category_id):
    result = view_category(repo, restaurant_id, category_id)

    if not result['success']:
        return redirect(url_for('restaurants.manage'))

    category = result['category']
    form     = EditCategory(category)
    if form.validate_on_submit():
        result = remove_category(repo, restaurant_id, category_id)
        if result['success']:
            return redirect(url_for(
                'restaurants.list_categories',
                restaurant_id=restaurant_id,
            ))

    view = {**result, 'form': form}
    return render_template('restaurants/add_edit_category.html', **view)

@bp.route('/manage/<restaurant_id>/products/add', methods=['GET', 'POST'])
@login_required
def add_product(restaurant_id):
    result = view_owned_restaurant(repo, restaurant_id, user.id)

    if not result['success']:
        return redirect(url_for('restaurants.home'))

    restaurant     = result['restaurant']
    category_names = [category['name'] for category in restaurant['categories']]
    form = AddProduct(category_names)
    if form.validate_on_submit():
        category_dto = [
            c for c in restaurant['categories']
            if c['name'] == form.category.data
        ]
        category_dto = category_dto[0]
        request = {
            'id'         : restaurant_id,
            'name'       : form.name.data,
            'description': form.description.data,
            'price'      : form.price.data,
            'categories' : [category_dto['id']],
        }
        result = add_product(repo, **request)

        if result['success']:
            params = {'restaurant_id': restaurant_id}
            return redirect(url_for('restaurants.list_products', **params))

    view = {**result, 'form': form}
    return render_template('restaurants/add_edit_product.html', **view)

@bp.route('/manage/<restaurant_id>/products')
@login_required
def list_products(restaurant_id):
    result = view_owned_restaurant(repo, restaurant_id, user.id)

    if not result['success']:
        return redirect(url_for('restaurants.manage'))

    return render_template('restaurants/list_products.html', **result)

@bp.route('/manage/<restaurant_id>/products/<product_id>', methods=['GET', 'POST'])
@login_required
def edit_product(restaurant_id, product_id):
    result = view_product(repo, restaurant_id, product_id)

    if not result['success']:
        return redirect(url_for('restaurants.list_products', slug=slug))

    restaurant = result['restaurant']
    product    = result['product']
    category   = product['categories'][0]
    form       = EditProduct(product, category)
    if form.validate_on_submit():
        if form.delete.data:
            result = remove_product(repo, restaurant_id, product_id)
            params = {'restaurant_id': restaurant_id}
            return redirect(url_for('restaurants.list_products', **params))

        if form.submit.data:
            request = {
                'id': restaurant_id,
                'product_id': product_id,
                'name': form.name.data,
                'description': form.description.data,
                'price': float(form.price.data),
                'category_ids': [category['id']],
            }
            result = edit_product(repo, **request)
            params = {'restaurant_id': restaurant_id}
            return redirect(url_for('restaurants.list_products', **params))

    view = {**result, 'form': form}
    return render_template('restaurants/add_edit_product.html', **view)

@bp.route('/manage/<restaurant_id>/qrcodes')
@login_required
def qrcodes(restaurant_id):
    result = view_owned_restaurant(repo, restaurant_id, user.id)

    if not result['success']:
        return redirect(url_for('restaurants.manage'))

    restaurant  = result['restaurant']
    slug        = restaurant['slug']
    public_href = f'{request.host_url}t/qrcode/{slug}'
    view        = {'restaurant': restaurant, 'public_href': public_href}
    return render_template('restaurants/generate_qrcodes.html', **view)

hacarta/application/restaurants/templates/restaurants/add_edit_category.html
{% extends 'base/sb-dash.html' %}

{% block title %}{{ restaurant.name }} - Categoria{% endblock %}

{% block topbar_content %}<h1 class="h3 mb-2 text-gray-800">Adicionar Categoria</h1>{% endblock %}

{% block sidebar %}{% include 'restaurants/include/sidebar.html' %}{% endblock %}

{% block page %}

  <form action="" method="post" novalidate>
    {{ form.hidden_tag() }}

    <div class="form-group">
      {{ form.name.label }}
      {{ form.name(class='form-control', placeholder='Nome') }}
      {% for error in form.name.errors %}
        <small class="form-text text-muted">{{ error }}</small>
      {% endfor %}
    </div>

    {% if form.submit %}
      {{ form.submit(class='btn btn-primary') }}
    {% endif %}
    {% if form.delete %}
      {{ form.delete(class='btn btn-danger') }}
    {% endif %}
  </form>

{% endblock %}

hacarta/application/restaurants/templates/restaurants/add_edit_product.html
{% extends 'base/sb-dash.html' %}

{% block title %}{{ restaurant.name }} - Produto{% endblock %}

{% block topbar_content %}<h1 class="h3 mb-2 text-gray-800">Adicionar Produto</h1>{% endblock %}

{% block sidebar %}{% include 'restaurants/include/sidebar.html' %}{% endblock %}

{% block page %}

  <form action="" method="post" novalidate>
    {{ form.hidden_tag() }}

    <div class="form-group">
      {{ form.name.label }}
      {{ form.name(class='form-control', placeholder='Nome') }}
      {% for error in form.name.errors %}
        <small class="form-text text-muted">{{ error }}</small>
      {% endfor %}
    </div>
    <div class="form-group">
      {{ form.description.label }}
      {{ form.description(class='form-control', placeholder='Descrição') }}
      {% for error in form.description.errors %}
        <small class="form-text text-muted">{{ error }}</small>
      {% endfor %}
    </div>
    <div class="form-group">
      {{ form.category.label }}
      {{ form.category(class='form-control', placeholder='Categoria') }}
      {% for error in form.category.errors %}
        <small class="form-text text-muted">{{ error }}</small>
      {% endfor %}
    </div>
    <div class="form-group">
      {{ form.price.label }}
      {{ form.price(class='form-control', placeholder='Preço') }}
      {% for error in form.price.errors %}
        <small class="form-text text-muted">{{ error }}</small>
      {% endfor %}
    </div>

    {% if form.submit %}
      {{ form.submit(class='btn btn-primary') }}
    {% endif %}
    {% if form.delete %}
      {{ form.delete(class='btn btn-danger') }}
    {% endif %}
  </form>

{% endblock %}

hacarta/application/restaurants/templates/restaurants/add_restaurant.html
{% extends 'base/sb-dash.html' %}

{% block title %}Adicionar Restaurante{% endblock %}

{% block topbar_content %}<h1 class="h3 mb-2 text-gray-800">Adicionar Restaurante</h1>{% endblock %}

{% block page %}
  <p class="mb-4">Preencha os dados abaixo para ter a página do seu restaurante disponível e adiconar produtos.</p>

  <form action="" method="post" novalidate>
    {{ form.hidden_tag() }}

    <div class="form-group">
      {{ form.name.label }}
      {{ form.name(class='form-control', placeholder='Nome') }}
      {% for error in form.name.errors %}
        <small id="emailHelp" class="form-text text-muted">{{ error }}</small>
      {% endfor %}
    </div>

    {{ form.submit(class='btn btn-primary') }}
  </form>

{% endblock %}

hacarta/application/restaurants/templates/restaurants/edit_restaurant.html
{% extends 'base/sb-dash.html' %}

{% block title %}{{ restaurant.name }} - Editar{% endblock %}

{% block topbar_content %}<h1 class="h3 mb-2 text-gray-800">Sobre o {{ restaurant.name }}</h1>{% endblock %}

{% block sidebar %}{% include 'restaurants/include/sidebar.html' %}{% endblock %}

{% block page %}
  <p class="mb-4">Altere o visual do seu menu e informações sobre o seu restaurante.</p>

  <form action="" method="post" novalidate>
    {{ form.hidden_tag() }}

    <div class="form-group">
      {{ form.name.label }}
      {{ form.name(class='form-control', placeholder='Nome') }}
      {% for error in form.name.errors %}
        <small class="form-text text-muted">{{ error }}</small>
      {% endfor %}
    </div>
    <div class="form-group">
      {{ form.slug.label }}
      {{ form.slug(class='form-control', placeholder='Url') }}
      {% for error in form.slug.errors %}
        <small class="form-text text-muted">{{ error }}</small>
      {% endfor %}
    </div>
    <div class="form-group">
      {{ form.description.label }}
      {{ form.description(id="edit-description", class='form-control', placeholder='Descrição') }}
      {% for error in form.description.errors %}
        <small class="form-text text-muted">{{ error }}</small>
      {% endfor %}
    </div>
    <div class="form-group">
      {{ form.footer.label }}
      {{ form.footer(id="edit-footer", class='form-control', placeholder='Informação de rodapé') }}
      {% for error in form.footer.errors %}
        <small class="form-text text-muted">{{ error }}</small>
      {% endfor %}
    </div>

    {{ form.submit(class='btn btn-primary') }}

    {{ simplemde.css }}
    {{ simplemde.js }}
    {{ simplemde.load_id("edit-description") }}
    {{ simplemde.load_id("edit-footer") }}
  </form>
{% endblock %}

hacarta/application/restaurants/templates/restaurants/generate_qrcodes.html
{% extends 'base/sb-dash.html' %}

{% block title %}{{ restaurant.name }} - QR Codes{% endblock %}

{% block topbar_content %}<h1 class="h3 mb-2 text-gray-800">QR Codes</h1>{% endblock %}

{% block sidebar %}{% include 'restaurants/include/sidebar.html' %}{% endblock %}

{% block page %}
  <p class="mb-4">Imprime e coloque os códigos nas mesas.</p>

  <img src="{{ qrcode(public_href) }}">

{% endblock %}

hacarta/application/restaurants/templates/restaurants/list_categories.html
{% extends 'base/sb-dash.html' %}

{% block title %}{{ restaurant.name }} - Categorias{% endblock %}

{% block topbar_content %}<h1 class="h3 mb-2 text-gray-800">Categorias</h1>{% endblock %}

{% block sidebar %}{% include 'restaurants/include/sidebar.html' %}{% endblock %}

{% block page %}
  <p class="mb-4">Organize o seu menu em categorias, crie ou apague categorias. Poderá depois adicionar a categoria aos produtos.</p>

  <div class="card shadow mb-4">
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>Nome</th>
              <th># produtos</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {% for category in restaurant.categories %}
              <tr>
                <td>{{ category.name }}</td>
                <td>{{ category.products|length }}</td>
                <td><a href="{{ url_for('restaurants.edit_category', restaurant_id=restaurant.id, category_id=category.id) }}">Editar</a></td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>

    <a href="{{ url_for('restaurants.add_category', restaurant_id=restaurant.id) }}" class="btn btn-primary btn-icon-split">
      <span class="text">Adicionar Categoria</span>
    </a>
  </div>

{% endblock %}

hacarta/application/restaurants/templates/restaurants/list_products.html
{% extends 'base/sb-dash.html' %}

{% block title %}{{ restaurant.name }} - Produtos{% endblock %}

{% block topbar_content %}<h1 class="h3 mb-2 text-gray-800">Produtos</h1>{% endblock %}

{% block sidebar %}{% include 'restaurants/include/sidebar.html' %}{% endblock %}

{% block page %}
  <p class="mb-4">Adicione produtos ao seu menu.</p>

  <div class="card shadow mb-4">
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>Nome</th>
              <th>Categoria</th>
              <th>Preço</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {% for product in restaurant.products %}
              <tr>
                <td>{{ product.name }}</td>
                <td>
                  {% for category in product.categories %}
                    {{ category.name }}
                    {% if not loop.last %}
                      ,
                    {% endif %}
                  {% endfor %}
                  </td>
                <td>{{ product.price }}€</td>
                <td><a href="{{ url_for('restaurants.edit_product', restaurant_id=restaurant.id, product_id=product.id) }}">Editar</a></td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>

    <a href="{{ url_for('restaurants.add_product', restaurant_id=restaurant.id) }}" class="btn btn-primary btn-icon-split">
      <span class="text">Adicionar Produto</span>
    </a>
  </div>

{% endblock %}

hacarta/application/restaurants/templates/restaurants/list_restaurants.html
{% extends 'base/sb-dash.html' %}

{% block title %}Meus Restaurantes{% endblock %}

{% block topbar_content %}<h1 class="h3 mb-2 text-gray-800">Meus Restaurantes</h1>{% endblock %}

{% block page %}
  <p class="mb-4">Adicione novos restaurantes ou selecione um existente para o editar.</p>

  <div class="card shadow mb-4">
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>Nome</th>
              <th>Ver</th>
              <th>Editar</th>
            </tr>
          </thead>
          <tbody>
            {% for restaurant in restaurants %}
              <tr>
                <td>{{ restaurant.name }}</td>
                <td><a href="{{ url_for('restaurants.home', slug=restaurant.slug) }}" >Ver</a></td>
                <td><a href="{{ url_for('restaurants.edit', restaurant_id=restaurant.id) }}" >Editar</a></td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>

    <a href="{{ url_for('restaurants.add') }}" class="btn btn-primary btn-icon-split">
      <span class="text">Adicionar Restaurante</span>
    </a>
  </div>
{% endblock %}

hacarta/application/restaurants/templates/restaurants/menu.html
{% extends "base/meal-template.html" %}

{% block title %}{{ restaurant.name }} - Menu{% endblock %}

{% block page %}
  <div class="section bg-light" id="section-menu" data-aos="fade-up">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-8">
          <ul class="nav site-tab-nav" id="pills-tab" role="tablist">
            {% if restaurant.categories|length > 0 %}
              <li class="nav-item">
                <a class="nav-link active" id="pills-{{ restaurant.categories[0].name }}-tab" data-toggle="pill" href="#pills-{{ restaurant.categories[0].name }}" role="tab" aria-controls="pills-{{ restaurant.categories[0].name }}" aria-selected="true">{{ restaurant.categories[0].name }}</a>
              </li>
            {% endif %}
            {% for category in restaurant.categories[1:] %}
              <li class="nav-item">
                <a class="nav-link" id="pills-{{ category.name }}-tab" data-toggle="pill" href="#pills-{{ category.name }}" role="tab" aria-controls="pills-{{ category.name }}" aria-selected="false">{{ category.name }}</a>
              </li>
            {% endfor %}
          </ul>
          <div class="tab-content" id="pills-tabContent">
            {% if restaurant.categories|length > 0 %}
              <div class="tab-pane fade active show" id="pills-{{ restaurant.categories[0].name }}" role="tabpanel" aria-labelledby="pills-{{ restaurant.categories[0].name }}-tab">

                {% for product in restaurant.categories[0].products %}
                  <div class="d-block d-md-flex menu-food-item">

                    <div class="text order-1 mb-3">
                      {% if product.image %}
                        <img src="{{ url_for('static', filename='meal-template/images/img_1.jpg') }}" alt="Image">
                      {% endif %}
                      <h3>{{ product.name }}</h3>
                      <p>{{ product.description }}</p>
                    </div>
                    <div class="price order-2">
                      <strong>{{ product.price }}€</strong>
                    </div>
                  </div> <!-- .menu-food-item -->
                {% endfor %}

              </div>
            {% endif %}
            {% for category in restaurant.categories[1:] %}
              <div class="tab-pane fade" id="pills-{{ category.name }}" role="tabpanel" aria-labelledby="pills-{{ category.name }}-tab">

                {% for product in category.products %}
                  <div class="d-block d-md-flex menu-food-item">

                    <div class="text order-1 mb-3">
                      {% if product.image %}
                        <img src="{{ url_for('static', filename='meal-template/images/img_1.jpg') }}" alt="Image">
                      {% endif %}
                      <h3>{{ product.name }}</h3>
                      <p>{{ product.description }}</p>
                    </div>
                    <div class="price order-2">
                      <strong>{{ product.price }}€</strong>
                    </div>
                  </div> <!-- .menu-food-item -->
                {% endfor %}

              </div>
            {% endfor %}

          </div>
        </div>

      </div>
    </div>
  </div>
{% endblock %}

hacarta/application/restaurants/templates/restaurants/restaurant.html
{% extends "base/meal-template.html" %}

{% block title %}{{ restaurant.name }}{% endblock %}

{% block page %}

<div class="cover_1 overlay bg-light">
  <div class="img_bg" style="background-image: url({{ url_for('static', filename='meal-template/images/slider-1.jpg') }});" data-stellar-background-ratio="0.5">
    <div class="container">
      <div class="row align-items-center justify-content-center text-center">
        <div class="col-md-10" data-aos="fade-up">
          <h2 class="heading mb-5">{{ restaurant.name }}</h2>
          <p><a href="{{ url_for('restaurants.menu', slug=restaurant.slug) }}" class="smoothscroll btn btn-outline-white px-5 py-3">Ver Menu</a></p>
        </div>
      </div>
    </div>
  </div>
</div> <!-- .cover_1 -->

<div class="section"  data-aos="fade-up">
  <div class="container">
    <div class="row section-heading justify-content-center mb-5">
      <div class="col-md-8 text-center">
        {{ restaurant.description|markdown }}
      </div>
    </div>
    <div class="row">

      <!-- <div class="ftco-46">
        <div class="ftco-46-row d-flex flex-column flex-lg-row">
          <div class="ftco-46-image" style="background-image: url({{ url_for('static', filename='meal-template/images/img_1.jpg') }});"></div>
          <div class="ftco-46-text ftco-46-arrow-left">
            <h4 class="ftco-46-subheading">Vegies</h4>
            <h3 class="ftco-46-heading">Beef Empanadas</h3>
            <p class="mb-5">Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
            <p><a href="#" class="btn-link">Learn More <span class="ion-android-arrow-forward"></span></a></p>
          </div>
          <div class="ftco-46-image" style="background-image: url({{ url_for('static', filename='meal-template/images/img_2.jpg') }});"></div>
        </div>

        <div class="ftco-46-row d-flex flex-column flex-lg-row">
          <div class="ftco-46-text ftco-46-arrow-right">
            <h4 class="ftco-46-subheading">Food</h4>
            <h3 class="ftco-46-heading">Buttermilk Chicken Jibaritos</h3>
            <p class="mb-5">A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>
            <p><a href="#" class="btn-link">Learn More <span class="ion-android-arrow-forward"></span></a></p>
          </div>
          <div class="ftco-46-image" style="background-image: url({{ url_for('static', filename='meal-template/images/img_3.jpg') }});"></div>
          <div class="ftco-46-text ftco-46-arrow-up">
            <h4 class="ftco-46-subheading">Food</h4>
            <h3 class="ftco-46-heading">Chicken Chimichurri Croquettes</h3>
            <p class="mb-5">Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life.</p>
            <p><a href="#" class="btn-link">Learn More <span class="ion-android-arrow-forward"></span></a></p>
          </div>
        </div>
      </div> -->

    </div>
  </div>
</div>

{% endblock %}